[package]
name = "common-macros"
version = "0.0.0"
edition = "2021"
publish = false

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1"
syn = "2"
quote = "1"

proc-macro2-diagnostics = "0.10.1"
