version = "Two"

max_width = 100
use_small_heuristics = "Max"

imports_indent = "Block"
imports_layout = "Mixed"
imports_granularity = "Module"
group_imports = "Preserve"
reorder_imports = true
reorder_modules = true
