[package]
name = "optimistic-oracle"
version = "0.0.0"
edition = "2021"
publish = false

[features]
serde = ["dep:serde", "serde_with"]

[dependencies]
solana-program = ">= 1.18, < 2.2"

borsh = { version = "0.10.4", features = ["const-generics"] }
thiserror = "1.0"
num-traits = "0.2.19"
num-derive = "0.4.2"

borsh1 = { version = "1.5.1", package = "borsh" }

serde = { version = "1.0", optional = true }
serde_with = { version = "3.9", optional = true }
