[package]
name = "common"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
solana-program = { workspace = true }

spl-token-2022 = { workspace = true }

common-macros = { path = "../common-macros" }
